services:
  mongo:
    image: mongo:7
    container_name: fruits
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: fruits-db
    volumes:
      - mongo_data:/data/db
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - fruits-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
    container_name: fruits-app
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017
      DB_NAME: fruits-db
      COLLECTION_NAME: fruits
    ports:
      - "3000:3000"
    networks:
      - fruits-net

networks:
  fruits-net:

volumes:
  mongo_data: