name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
      - feature/bonus-part
  workflow_dispatch:

env:
  RG: rg-fruits-app
  APP_NAME: fruits-app
  ACR_NAME: devopshometask
  IMAGE_NAME: fruits-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name $ACR_NAME

      - name: Build and push image to ACR
        run: |
          az acr build \
            --registry $ACR_NAME \
            --image $IMAGE_NAME:$IMAGE_TAG \
            ./app

      - name: Update Container App image
        run: |
          az containerapp update \
            --name $APP_NAME \
            --resource-group $RG \
            --container-name fruits-app \
            --image $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG

      - name: Show Container App URL
        run: |
          az containerapp show \
            --name $APP_NAME \
            --resource-group $RG \
            --query properties.configuration.ingress.fqdn \
            -o tsv